package com.smartcommunity.pojo;

public class Modules {
	/** add_y */
	private java.util.List<Operations> operations;
	
	public java.util.List<Operations> getOperations() {
		return operations;
	}

	public void setOperations(java.util.List<Operations> operations) {
		this.operations = operations;
	}

	/** addend_y */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.id
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.name
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.package_name
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.description
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.id
     *
     * @return the value of modules.id
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.id
     *
     * @param id the value for modules.id
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.name
     *
     * @return the value of modules.name
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.name
     *
     * @param name the value for modules.name
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.package_name
     *
     * @return the value of modules.package_name
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.package_name
     *
     * @param packageName the value for modules.package_name
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.description
     *
     * @return the value of modules.description
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.description
     *
     * @param description the value for modules.description
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}