package com.smartcommunity.pojo;

public class Operations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operations.id
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operations.moduleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private Integer moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operations.address
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operations.short_desc
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private String shortDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operations.long_desc
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private String longDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operations.id
     *
     * @return the value of operations.id
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operations.id
     *
     * @param id the value for operations.id
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operations.moduleid
     *
     * @return the value of operations.moduleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operations.moduleid
     *
     * @param moduleid the value for operations.moduleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operations.address
     *
     * @return the value of operations.address
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operations.address
     *
     * @param address the value for operations.address
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operations.short_desc
     *
     * @return the value of operations.short_desc
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public String getShortDesc() {
        return shortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operations.short_desc
     *
     * @param shortDesc the value for operations.short_desc
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc == null ? null : shortDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operations.long_desc
     *
     * @return the value of operations.long_desc
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public String getLongDesc() {
        return longDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operations.long_desc
     *
     * @param longDesc the value for operations.long_desc
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc == null ? null : longDesc.trim();
    }
}