package com.smartcommunity.pojo;

public class RoleModuleOperation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module_operation.id
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module_operation.roleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module_operation.moduleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private Integer moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module_operation.operationid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    private Integer operationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module_operation.id
     *
     * @return the value of role_module_operation.id
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module_operation.id
     *
     * @param id the value for role_module_operation.id
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module_operation.roleid
     *
     * @return the value of role_module_operation.roleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module_operation.roleid
     *
     * @param roleid the value for role_module_operation.roleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module_operation.moduleid
     *
     * @return the value of role_module_operation.moduleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module_operation.moduleid
     *
     * @param moduleid the value for role_module_operation.moduleid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module_operation.operationid
     *
     * @return the value of role_module_operation.operationid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public Integer getOperationid() {
        return operationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module_operation.operationid
     *
     * @param operationid the value for role_module_operation.operationid
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    public void setOperationid(Integer operationid) {
        this.operationid = operationid;
    }
}