package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Modules;
import com.smartcommunity.pojo.ModulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int countByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int deleteByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int insert(Modules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int insertSelective(Modules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    List<Modules> selectByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    Modules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") Modules record, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int updateByExample(@Param("record") Modules record, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int updateByPrimaryKeySelective(Modules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbggenerated Thu Apr 30 10:24:28 CST 2015
     */
    int updateByPrimaryKey(Modules record);
    /** add_y */
    List<Modules> getModulesAndOperations();
    List<Modules> getModulesAndOperationsByRoleId(@Param("roleId") Integer roleId);
    /**addend_y */
}