package com.smartcommunity.mapper;

import com.smartcommunity.pojo.Operations;
import com.smartcommunity.pojo.OperationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int countByExample(OperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int deleteByExample(OperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int insert(Operations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int insertSelective(Operations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    List<Operations> selectByExample(OperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    Operations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") Operations record, @Param("example") OperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByExample(@Param("record") Operations record, @Param("example") OperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByPrimaryKeySelective(Operations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operations
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByPrimaryKey(Operations record);
}