package com.smartcommunity.mapper;

import com.smartcommunity.pojo.RoleModuleOperation;
import com.smartcommunity.pojo.RoleModuleOperationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleModuleOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int countByExample(RoleModuleOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int deleteByExample(RoleModuleOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int insert(RoleModuleOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int insertSelective(RoleModuleOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    List<RoleModuleOperation> selectByExample(RoleModuleOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    RoleModuleOperation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoleModuleOperation record, @Param("example") RoleModuleOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByExample(@Param("record") RoleModuleOperation record, @Param("example") RoleModuleOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByPrimaryKeySelective(RoleModuleOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module_operation
     *
     * @mbggenerated Thu Apr 30 10:18:19 CST 2015
     */
    int updateByPrimaryKey(RoleModuleOperation record);
}